// STOP POINT VALUE
export const FIRST_POINT_PHASE = 'FIRST_POINT_PHASE';
export const SECOND_POINT_PHASE = 'SECOND_POINT_PHASE';
export const FINAL_POINT_PHASE = 'FINAL_POINT_PHASE';
export const FINAL_SCREEN_PHASE = 'FINAL_SCREEN_PHASE';