// STOP POINT VALUE
export const FIRST_POINT_STAGE = 'FIRST_POINT_STAGE';
export const SECOND_POINT_STAGE = 'SECOND_POINT_STAGE';
export const FINAL_POINT_STAGE = 'FINAL_POINT_STAGE';
export const FINAL_SCREEN_STAGE = 'FINAL_SCREEN_STAGE';