import { BOTTOM_TO_TOP, TOP_TO_BOTTOM } from './hiddenArea'
import {
    DIFF,
    INITIAL_LINE_POSITION,
    SECOND_LINE_POSITION,
    THIRD_LINE_POSITION,
    FOURTH_LINE_POSITION,
    INITIAL_TICK_POSITION,
    SECOND_TICK_POSITION,
    THIRD_TICK_POSITION,
    FOURTH_TICK_POSITION,
    FINAL_TICK_VALUE,
    START_POINT_X,
    FINISH_POINT_X,
    START_POINT_Y,
    MIDDLE_POINT_Y,
    FINISH_SCREEN_X,
    FINISH_SCREEN_Y,
} from './positions'
import {
    FIRST_POINT_STAGE,
    SECOND_POINT_STAGE,
    FINAL_SCREEN_STAGE,
    POINT_INTERVAL_FINAL_VALUE
} from "./stages"

import {
    LINE_INTERVAL_START,
    LINE_INTERVAL_PAUSE,
} from './lineInterval'



export {
    BOTTOM_TO_TOP,
    TOP_TO_BOTTOM,
    DIFF,
    INITIAL_LINE_POSITION,
    SECOND_LINE_POSITION,
    THIRD_LINE_POSITION,
    FOURTH_LINE_POSITION,
    INITIAL_TICK_POSITION,
    SECOND_TICK_POSITION,
    THIRD_TICK_POSITION,
    FOURTH_TICK_POSITION,
    FINAL_TICK_VALUE,
    START_POINT_X,
    FINISH_POINT_X,
    START_POINT_Y,
    MIDDLE_POINT_Y,
    FINISH_SCREEN_X,
    FINISH_SCREEN_Y,
    FIRST_POINT_STAGE,
    SECOND_POINT_STAGE,
    FINAL_SCREEN_STAGE,
    LINE_INTERVAL_START,
    LINE_INTERVAL_PAUSE,
    POINT_INTERVAL_FINAL_VALUE
};