import {
    BOTTOM_TO_TOP,
    TOP_TO_BOTTOM
} from './hiddenArea';

import {
    DIFF,
    INITIAL_POSITION,
    SECOND_POSITION,
    THIRD_POSITION,
    FINAL_POSITION,
    FINAL_TICK_VALUE,
} from './linePositions';

import {
    START_POINT_X,
    FINISH_POINT_X,
    START_POINT_Y,
    MIDDLE_POINT_Y,
    FINISH_SCREEN_X,
    FINISH_SCREEN_Y,
} from './pointPositions';


import {
    FIRST_POINT_STAGE,
    SECOND_POINT_STAGE,
    FINAL_SCREEN_STAGE,
} from "./stages";

import {
    LINE_INTERVAL_START,
    LINE_INTERVAL_PAUSE,
} from './lineInterval';

import {
    POINT_INTERVAL_FINAL_VALUE
} from './pointValues';

import {
    INITIAL_POSITION_TYPE,
    FIRST_POSITION_TYPE,
    SECOND_POSITION_TYPE,
    THIRD_POSITION_TYPE,
    FINAL_POSITION_TYPE
} from './positionType'



export {
    BOTTOM_TO_TOP,
    TOP_TO_BOTTOM,
    DIFF,
    FINAL_TICK_VALUE,
    START_POINT_X,
    FINISH_POINT_X,
    START_POINT_Y,
    MIDDLE_POINT_Y,
    FINISH_SCREEN_X,
    FINISH_SCREEN_Y,
    FIRST_POINT_STAGE,
    SECOND_POINT_STAGE,
    FINAL_SCREEN_STAGE,
    LINE_INTERVAL_START,
    LINE_INTERVAL_PAUSE,
    POINT_INTERVAL_FINAL_VALUE,
    INITIAL_POSITION_TYPE,
    FIRST_POSITION_TYPE,
    SECOND_POSITION_TYPE,
    THIRD_POSITION_TYPE,
    FINAL_POSITION_TYPE,
    INITIAL_POSITION,
    SECOND_POSITION,
    THIRD_POSITION,
    FINAL_POSITION,
};