export const DIFF = 67;
// LINE Y POSITION VALUES
export const INITIAL_LINE_POSITION = 29.5;
export const SECOND_LINE_POSITION = INITIAL_LINE_POSITION + DIFF;
export const THIRD_LINE_POSITION = INITIAL_LINE_POSITION + DIFF * 2;
export const FOURTH_LINE_POSITION = INITIAL_LINE_POSITION + DIFF * 3;
// TICK Y POSITION VALUES
export const INITIAL_TICK_POSITION = 23;
export const SECOND_TICK_POSITION = INITIAL_TICK_POSITION + DIFF;
export const THIRD_TICK_POSITION = INITIAL_TICK_POSITION + DIFF * 2;
export const FOURTH_TICK_POSITION = INITIAL_TICK_POSITION + DIFF * 3;
export const FINAL_TICK_VALUE = 1;

// POINT AXES CONTROL VALUES
export const START_POINT_X = 0
export const FINISH_POINT_X = 170
export const START_POINT_Y = 240
export const MIDDLE_POINT_Y = 60;
export const FINISH_SCREEN_X = 40;
export const FINISH_SCREEN_Y = 50;