export const INITIAL_POSITION = 'INITIAL_POSITION';
export const FIRST_POSITION = 'FIRST_POSITION';
export const SECOND_POSITION = 'SECOND_POSITION';
export const THIRD_POSITION = 'THIRD_POSITION';
export const FINAL_POSITION = 'FINAL_POSITION';