export const INITIAL_POSITION_TYPE = 'INITIAL_POSITION';
export const FIRST_POSITION_TYPE = 'FIRST_POSITION';
export const SECOND_POSITION_TYPE = 'SECOND_POSITION';
export const THIRD_POSITION_TYPE = 'THIRD_POSITION';
export const FINAL_POSITION_TYPE = 'FINAL_POSITION';